version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: lishe
      POSTGRES_PASSWORD: lishe
      POSTGRES_DB: lishe
    ports:
      - "4322:5432"
    volumes:
      - lishe_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6079:6379"

volumes:
  lishe_pg_data: