KENYAN_FOODS_SEED = [
    {
        "name_en": "Ugali",
        "name_sw": "Ugali",
        "category": "staple",
        "serving_size_g": 250,
        "calories_kcal": 365,
        "protein_g": 7.4,
        "carbs_g": 80.0,
        "fat_g": 1.2,
        "fiber_g": 3.0,
        "key_micronutrients": {"iron_mg": 1.2, "magnesium_mg": 25},
        "common_allergens": [],
    },
    {
        "name_en": "Sukuma wiki",
        "name_sw": "Sukuma wiki",
        "category": "vegetable",
        "serving_size_g": 150,
        "calories_kcal": 45,
        "protein_g": 3.3,
        "carbs_g": 6.0,
        "fat_g": 0.6,
        "fiber_g": 3.6,
        "key_micronutrients": {"vitamin_a_mcg": 500, "vitamin_c_mg": 60},
        "common_allergens": [],
    },
    {
        "name_en": "Githeri",
        "name_sw": "Githeri",
        "category": "staple",
        "serving_size_g": 300,
        "calories_kcal": 420,
        "protein_g": 16.0,
        "carbs_g": 70.0,
        "fat_g": 5.0,
        "fiber_g": 12.0,
        "key_micronutrients": {"iron_mg": 3.5, "folate_mcg": 130},
        "common_allergens": [],
    },
    {
        "name_en": "Nyama choma",
        "name_sw": "Nyama choma",
        "category": "protein",
        "serving_size_g": 200,
        "calories_kcal": 490,
        "protein_g": 42.0,
        "carbs_g": 0.0,
        "fat_g": 34.0,
        "fiber_g": 0.0,
        "key_micronutrients": {"iron_mg": 4.0, "zinc_mg": 8.0},
        "common_allergens": [],
    },
    {
        "name_en": "Chapati",
        "name_sw": "Chapati",
        "category": "staple",
        "serving_size_g": 60,
        "calories_kcal": 200,
        "protein_g": 4.5,
        "carbs_g": 30.0,
        "fat_g": 7.0,
        "fiber_g": 1.5,
        "key_micronutrients": {"iron_mg": 1.0},
        "common_allergens": ["gluten"],
    },
    {
        "name_en": "Mandazi",
        "name_sw": "Mandazi",
        "category": "snack",
        "serving_size_g": 60,
        "calories_kcal": 220,
        "protein_g": 3.8,
        "carbs_g": 28.0,
        "fat_g": 10.0,
        "fiber_g": 1.0,
        "key_micronutrients": {},
        "common_allergens": ["gluten"],
    },
    {
        "name_en": "Matoke",
        "name_sw": "Matoke",
        "category": "staple",
        "serving_size_g": 200,
        "calories_kcal": 190,
        "protein_g": 2.0,
        "carbs_g": 45.0,
        "fat_g": 0.5,
        "fiber_g": 3.5,
        "key_micronutrients": {"potassium_mg": 500},
        "common_allergens": [],
    },
    {
        "name_en": "Terere (amaranth greens)",
        "name_sw": "Terere",
        "category": "vegetable",
        "serving_size_g": 120,
        "calories_kcal": 35,
        "protein_g": 3.5,
        "carbs_g": 5.0,
        "fat_g": 0.4,
        "fiber_g": 3.0,
        "key_micronutrients": {"calcium_mg": 210, "iron_mg": 2.3},
        "common_allergens": [],
    },
    {
        "name_en": "Managu (African nightshade)",
        "name_sw": "Managu",
        "category": "vegetable",
        "serving_size_g": 120,
        "calories_kcal": 33,
        "protein_g": 3.0,
        "carbs_g": 4.5,
        "fat_g": 0.5,
        "fiber_g": 2.8,
        "key_micronutrients": {"vitamin_a_mcg": 450, "iron_mg": 2.0},
        "common_allergens": [],
    },
    {
        "name_en": "Omena (silver cyprinid)",
        "name_sw": "Omena",
        "category": "protein",
        "serving_size_g": 100,
        "calories_kcal": 180,
        "protein_g": 24.0,
        "carbs_g": 0.0,
        "fat_g": 8.0,
        "fiber_g": 0.0,
        "key_micronutrients": {"calcium_mg": 1500, "iron_mg": 4.0},
        "common_allergens": ["fish"],
    },
    {
        "name_en": "Ndengu (green grams)",
        "name_sw": "Ndengu",
        "category": "legume",
        "serving_size_g": 180,
        "calories_kcal": 210,
        "protein_g": 14.0,
        "carbs_g": 36.0,
        "fat_g": 0.8,
        "fiber_g": 8.0,
        "key_micronutrients": {"folate_mcg": 160, "iron_mg": 2.8},
        "common_allergens": [],
    },
    {
        "name_en": "Pilau",
        "name_sw": "Pilau",
        "category": "staple",
        "serving_size_g": 300,
        "calories_kcal": 430,
        "protein_g": 10.0,
        "carbs_g": 68.0,
        "fat_g": 12.0,
        "fiber_g": 2.0,
        "key_micronutrients": {"iron_mg": 1.8},
        "common_allergens": [],
    },
    {
        "name_en": "Mukimo",
        "name_sw": "Mukimo",
        "category": "staple",
        "serving_size_g": 250,
        "calories_kcal": 310,
        "protein_g": 6.5,
        "carbs_g": 58.0,
        "fat_g": 5.5,
        "fiber_g": 6.0,
        "key_micronutrients": {"potassium_mg": 550, "vitamin_a_mcg": 300},
        "common_allergens": [],
    },
    {
        "name_en": "Uji",
        "name_sw": "Uji",
        "category": "beverage",
        "serving_size_g": 250,
        "calories_kcal": 150,
        "protein_g": 3.5,
        "carbs_g": 28.0,
        "fat_g": 2.0,
        "fiber_g": 2.0,
        "key_micronutrients": {"iron_mg": 1.5},
        "common_allergens": ["gluten"],
    },
]