"""initial schema

Revision ID: 3bc1e1de3b2c
Revises: 
Create Date: 2026-08-16 00:36:48.147899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '3bc1e1de3b2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the pgvector extension is available for the VECTOR type
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_sw', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('serving_size_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('key_micronutrients', sa.JSON(), nullable=False),
    sa.Column('common_allergens', sa.JSON(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_level'), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('goal', sa.Enum('lose_weight', 'maintain', 'gain_weight', 'manage_condition', name='goal'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_items', sa.JSON(), nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('source', sa.Enum('chat', 'photo', 'manual', name='meal_source'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'tool', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('meal_logs')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('food_items')
    # ### end Alembic commands ###
